version: '2'
services:
  redis:
    image: redis

  postgresql:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  django:
    build: docker/django
    ports:
      - 8000:80
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
    volumes:
      - ./versionmgr:/opt/app
      - ./requirements.txt:/opt/requirements.txt
