# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='version.Application'),
        ),
        migrations.AlterField(
            model_name='version',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='version.Host'),
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
