# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 04:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0003_auto_20160718_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 19, 4, 30, 34, 697227, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
