# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0006_auto_20160730_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.Application')),
            ],
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='host',
        ),
        migrations.RemoveField(
            model_name='version',
            name='application',
        ),
        migrations.RemoveField(
            model_name='version',
            name='deployment',
        ),
        migrations.RemoveField(
            model_name='version',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='version',
            name='uri',
        ),
        migrations.AddField(
            model_name='appinstance',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='version.Deployment'),
        ),
        migrations.AddField(
            model_name='appinstance',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.Host'),
        ),
        migrations.AddField(
            model_name='appinstance',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.Version'),
        ),
    ]
