# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0007_auto_20160827_1338'),
    ]

    operations = [
        migrations.RenameModel(
            'AppInstance',
            'Service',
        ),
        migrations.AddField(
            model_name='service',
            name='arguments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deploymentattribute',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='version.Deployment'),
        ),
        migrations.AlterField(
            model_name='service',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='version.Application'),
        ),
        migrations.AlterField(
            model_name='service',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='version.Deployment'),
        ),
        migrations.AlterField(
            model_name='service',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='version.Host'),
        ),
        migrations.AlterField(
            model_name='service',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='version.Version'),
        ),
    ]
