# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0009_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='version.Customer')),
            ],
        ),
    ]
