# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0010_customerattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='deployment',
        ),
        migrations.AddField(
            model_name='customer',
            name='deployments',
            field=models.ManyToManyField(related_name='customers', to='version.Deployment'),
        ),
    ]
