# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 14:55
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0015_auto_20161007_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'permissions': (('view_version', 'Can see version data'),)},
        ),
    ]
