# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 14:55
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


def create_permissions(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    perm = Permission.objects.get(codename="view_version")
    group, _ = Group.objects.get_or_create(
        name=settings.REGISTERED_GROUP
    )
    group.permissions.add(perm)
    group.save()

def revert_components(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name=settings.REGISTERED_GROUP).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0015_auto_20161007_1452'),
    ]

    operations = [
        migrations.RunPython(
            create_permissions,
            revert_components
        ),
    ]
