# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('version', '0017_register-group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='applicationattribute',
            name='application',
        ),
        migrations.RemoveField(
            model_name='clusterattribute',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='customerattribute',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='hostattribute',
            name='host',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.RemoveField(
            model_name='releaseattribute',
            name='release',
        ),
        migrations.DeleteModel(
            name='ApplicationAttribute',
        ),
        migrations.DeleteModel(
            name='ClusterAttribute',
        ),
        migrations.DeleteModel(
            name='CustomerAttribute',
        ),
        migrations.DeleteModel(
            name='HostAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ReleaseAttribute',
        ),
    ]
